apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-webapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/geonwoo-allganize/helm-test.git
    targetRevision: HEAD
    path: simple-webapp
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 