apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: {{ .Release.Name }}